server:
  port: 8080
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: spring-kafka-retrier-application
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:19092,localhost:29092,localhost:39092}
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        Event-out-0:
          destination: event_topic
          content-type: application/json
          group: ${spring.application.name}
          producer:
            partition-count: 3
        Event-in-0:
          destination: event_topic
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            max-attempts: 5
            back-off-initial-interval: 15000
            back-off-max-interval: 240000
            back-off-multiplier: 2
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
